name: discord-mod-bot
workers:
  - name: moderation-bot
    github:
      repo: EkuboProtocol/discord-mod-bot
      branch: main
      deploy_on_push: true
    source_dir: /
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    build_command: npm install
    run_command: npm start
    envs:
      - key: DISCORD_TOKEN
        type: SECRET
        scope: RUN_TIME
      - key: DISCORD_SERVER_ID
        type: SECRET
        scope: RUN_TIME
      - key: OPENAI_API_KEY
        type: SECRET
        scope: RUN_TIME
      - key: WELCOME_CHANNEL_ID
        value: '1119209474851356716'
        scope: RUN_TIME
      - key: NOTIFICATION_CHANNEL_ID
        value: '1119209950351204443'
        scope: RUN_TIME
      - key: EXCLUDED_ROLES
        value: 1119220820506583080,1120203566007713913,1205155966778343484
        scope: RUN_TIME
      - key: TIMEOUT_DURATION
        value: '10080'
        scope: RUN_TIME
      - key: OPENAI_MODEL
        value: gpt-4o-mini
        scope: RUN_TIME
      - key: IGNORED_PHRASES
        value: gm
        scope: RUN_TIME
      - key: CONTEXT_MESSAGE_COUNT
        value: '5'
        scope: RUN_TIME
      - key: LOG_LEVEL
        value: info
        scope: RUN_TIME